# Generated by Django 5.0.6 on 2024-07-03 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_user_is_2fa_enabled_emailverificationcode_and_more'),
    ]
