# Generated by Django 5.0.6 on 2024-07-03 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_session_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(default='', max_length=40)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('user_agent', models.CharField(default='NIL', max_length=255)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
