# Generated by Django 5.0.6 on 2024-07-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_session_expiry_time_and_more'),
    ]

