# Generated by Django 5.0.6 on 2024-07-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_session_ip_address_alter_session_session_key_and_more'),
    ]

    
